---

- name: release > Set
  set_fact:
    __elao_deploy_release: "{{ lookup('pipe', 'date -u +%Y%m%d%H%M%SZ') }}"
  run_once: true
  when: __elao_deploy_release is not defined
  delegate_to: 127.0.0.1

- include: "release/{{ elao_deploy_strategy | default('git') }}.yml"
