---

- name: release/git > Cached repository
  git:
    repo:           "{{ elao_deploy_git_repo }}"
    dest:           "{{ elao_deploy_dir_shared ~ '/cached-copy' }}"
    version:        "{{ elao_deploy_git_version }}"
    accept_hostkey: true
    update:         yes

- name: release/git > Export repository
  command: git checkout-index -f -a --prefix="{{ elao_deploy_dir_releases ~ '/' ~ __elao_deploy_release ~ '/' }}"
  args:
    chdir: "{{ elao_deploy_dir_shared ~ '/cached-copy' }}"
